feat: add PR title check workflow
hiero-ledger/hiero-json-rpc-relay pull request #1942
Opened 2023-11-30 10:16 UTC by georgi-l95

**Description**:
This PR adds workflow, which is responsible for checking the title of the PR and if it's compliant with the Conventional Commits standard

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-12-01 08:58 UTC, isavov approved these changes

2023-12-01 17:18 UTC, AlfredoG87 requested changes
Could we add a note on `README.md` with what is that standard?

Maybe under the `Contributing` section?

2023-12-05 13:38 UTC, georgi-l95 commented
@AlfredoG87 Agree with you, but I think this should be included in the contribution guide, more so because all PRs in all repos will need to comply with this rule. Not sure, if we should clutter the readme here.

2023-12-05 16:22 UTC, AlfredoG87 approved these changes

2023-12-11 20:52 UTC, Nana-EC commented
> > @AlfredoG87 Agree with you, but I think this should be included in the contribution guide, more so because all PRs in all repos will need to comply with this rule. Not sure, if we should clutter the readme here.
> 
> yeah, I agree with you that this should be on contributing guide. do we have one? 😅

Yeah you can open a ticket here https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md

2023-12-11 21:00 UTC, Nana-EC commented on .github/workflows/flow-pr-title-check.yml
> +        uses: aslafy-z/conventional-pr-title-action@v3
Q: does this support things like checking if labels are assigned and milestones set etc?

2023-12-14 05:03 UTC, Nana-EC approved these changes

2023-12-18 17:33 UTC, merged